# Generated by Django 3.2.20 on 2023-09-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_type', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
