# Generated by Django 3.2.20 on 2023-08-14 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbi_app', '0002_auto_20230813_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='heart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='content',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='takeaway_available',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
