# Generated by Django 3.2.20 on 2023-09-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0003_news_info_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='info_type',
            new_name='article',
        ),
    ]
