# Generated by Django 3.2.20 on 2023-09-01 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0005_rename_info_type_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbi_app.article'),
        ),
    ]
