# Generated by Django 3.2.20 on 2023-09-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0006_alter_news_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='article',
            new_name='category',
        ),
    ]
