# Generated by Django 3.2.20 on 2023-09-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0007_rename_article_news_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
