# Generated by Django 3.2.20 on 2023-08-24 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0011_auto_20230824_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
