# Generated by Django 3.2.20 on 2023-08-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0012_remove_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
