# Generated by Django 3.2.20 on 2023-08-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=80, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('approved', models.BooleanField(default=False, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pbi_app.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
