# Generated by Django 3.2.20 on 2023-08-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0014_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
