# Generated by Django 3.2.20 on 2023-08-24 08:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder_image', max_length=255, verbose_name='image'),
        ),
    ]
