# Generated by Django 3.2.20 on 2023-08-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0018_alter_post_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
