# Generated by Django 3.2.20 on 2023-08-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0020_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
