# Generated by Django 3.2.20 on 2023-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0021_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, default='placeholder_image', upload_to='images/'),
        ),
    ]
