# Generated by Django 3.2.20 on 2023-08-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0022_alter_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='placeholder_image', upload_to='images/'),
        ),
    ]
