# Generated by Django 3.2.20 on 2023-08-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0024_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
