# Generated by Django 3.2.20 on 2023-08-30 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbi_app', '0025_remove_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('featured_image', models.ImageField(blank=True, default='placeholder_image', upload_to='images/')),
                ('likes', models.ManyToManyField(blank=True, related_name='gallery_like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
