# Generated by Django 3.2.20 on 2023-08-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbi_app', '0027_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
